version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=rcontrol
      - POSTGRES_PASSWORD=ct112938
    ports:
     - "8006:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8005:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=rcontrol
      - POSTGRES_PASSWORD=ct112938
    depends_on:
      - db
